### ISSUE TITLE
Turtle Chunk unloads, no marker entity created

### ISSUE THREAD

**Issue by ToasterUwU** [Timer00/turtlechunkloader#2]
Hey its me again.

For the sake of clean Issues with a specific purpose i make a different one for this. 

So i checked how to exactly install a datapack, and i seemed to have figured it out.
1. I downloaded the repo as a zip
2. I unpacked the zip to have everything as a folder
3. I copied that folder into the datapacks folder of the world
4. I restarted the server

Now when i do `/datapacks list` i can see a bunch of things coming from my Fabric Mods, and at the very end it shows "file/turtlechunkloader (world)" in grey, the same as the vanilla thing at the beginning. If i hover over it there is a tooltip saying "Turtle chunk and surrounding are loaded."

So im pretty sure i installed it right and it loaded properly and everything. However, when i place a mining turtle down (i only have one) and then tell it to go mine in a straight line, then make sure i get away from it enough to have the chunk unload unless the datapack works, and come back, the turtle has stopped working. 
So it seems the chunk unloads. So instead i tried picking it up and placing it again, and using the command `/kill @e[type=marker, limit=1, sort=nearest]` to just check if there is an entity named marker as there should be.  And no, when i use the command i get "No entity found" in red, so it seems like the marker is never created.

Dont stress yourself out over this, i will survive without it. Just wanted to report it to you so that you are aware and have the chance to find the issue and maybe fix it.
Or maybe i did something wrong and dont realize it. 

Happy to give you any info you would need, so ask away.

**Comment by Timer00** [comment]
Hey! Thanks for the detailed report, it should be a simple fix, I forgot to tell you earlier you also need to install this other datapack: https://github.com/Aeldrion/Iris 

It's pretty clear when the turtlechunkloader is working since you'll get a sound on placing it down and particle effects. 

Let me know if that solves it :)

**Comment by Timer00** [comment]
Your datapack list should look something like this: 
<img width="563" alt="image" src="https://github.com/Timer00/turtlechunkloader/assets/19307482/f65072bb-b6eb-4e4a-8037-901b71663bfd">

**Comment by ToasterUwU** [comment]
Ok, i tried that right away, and it doesnt seem to fix it. I was missing Iris, but adding doesnt fix it.

![image](https://github.com/Timer00/turtlechunkloader/assets/43654377/743bc22d-ed8e-48ef-818e-bee31387fd5f)
Both are loaded, but when i place down the mining turtle nothing happens, and there also is no entity, just like before.

**Comment by Timer00** [comment]
Hey! I've updated the repo to contain both datapacks, that should make it easier. There is some configuration I had done within Iris to support computercraft. In the future I hope I can code my own raycasting to remove this reliance on an external lib.

**Comment by ToasterUwU** [comment]
Makes sense, i will try it in a bit and report back. 

Thanks for the effort and caring about a strangers experience using your work!

**Comment by ToasterUwU** [comment]
AAAAAAAAAA MY COMPUTER IS PRACTICING BLACK MAGIC

But seriously, it works now, thanks a lot. I can finally send the little buddy on a mining expedition without following him around
